name: psychotherapie-seliger
ingress:
  hostname: ""
secretStore: ""
customerName: ""
image:
  repository: europe-west10-docker.pkg.dev/psychotherapie-seliger-adm/images/psychotherapie-seliger
  tag: main-334-927bec6
