apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcr-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: ClusterSecretStore
  target:
    name: gcr-credentials
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: gcr-dockerconfigjson
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: ClusterSecretStore
  target:
    name: app-secrets
  data:
    - secretKey: database-url
      remoteRef:
        key: {{ .Values.name }}-database-url
    - secretKey: google-client-id
      remoteRef:
        key: {{ .Values.name }}-google-client-id
    - secretKey: google-client-secret
      remoteRef:
        key: {{ .Values.name }}-google-client-secret
    - secretKey: nextauth-secret
      remoteRef:
        key: {{ .Values.name }}-nextauth-secret
    - secretKey: pdf-owner-password
      remoteRef:
        key: {{ .Values.name }}-pdf-owner-password
