apiVersion: v1
kind: Service
metadata:
  namespace: argocd
  name: {{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 3000
